### ISSUE TITLE
Discussion on a Proposal

### ISSUE THREAD

**Issue by xiriloj-installlinux** [DecentralizedCAN/CAN#5]
**Describe the bug**
https://www.climatecan.org/solver/7YvUqr/solution/lNDt8y 
I want to participate in the discussion and want to post something, but it says: "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

Maybe it would be good, if you would put a date on that error message, so that you can look at the related log easily.
**To Reproduce**
1. Go to https://www.climatecan.org/solver/7YvUqr/solution/lNDt8y 

2. Click on the textbox and write something
3. Click on send

**Expected behavior**
Like in a normal discussion

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser Brave Browser Nightly (Brave uses the same engine as chrome)
 - Version Version 0.72.64 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)

**Comment by DecentralizedCAN** [comment]
I think I fixed this error. Thanks.
